### ISSUE TITLE
qt5 support?

### ISSUE THREAD

**Issue by alexmyczko** [xvass/UserManager#5]
Is there plans for a qt5 update?

https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5

**Comment by xen0vas** [comment]
sure but for now some bug fixing first..

**Comment by xen0vas** [comment]
> Is there plans for a qt5 update?
> 
> https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5

**Comment by xen0vas** [comment]
> Is there plans for a qt5 update?
> 
> https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5

Updated to qt5  :)
