### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by alexmyczko** [xvass/UserManager#8]
cool, builds and runs with qt5, but when i start it and click any user:

```
# ./UserManager
zsh: segmentation fault  ./UserManager
```

could you tag a new release/version?

could you drop images/* from future tarball releases?

**Comment by xen0vas** [comment]
yep i know .. i'm searching it.. @alexmyczko .This bug might be related with Qt5 GUI functions because i see the behaviour changes when maximizing the MainWindow. I will keep investigating. Further checks showing that there is a problem with malloc.. The problem comes perhaps at the phase of initialisation.. If you open the app and press reload then the app wont crash..

**Comment by alexmyczko** [comment]
do you know nologin hushlogin issue issue.net motd cron.allow ftpusers shells?  ok it is a UserManager but they are kind of related to usermanagement somehow, maybe there are more...

**Comment by xen0vas** [comment]
@alexmyczko, sure these shells could be added in later releases. I Will keep it in backlog in order to provide the relevant implementation. Thanks for mentioning.

**Comment by alexmyczko** [comment]
These are not shells, but special configuration files for special cases. I will explain them here in detail later.

https://manpages.debian.org/buster/manpages/nologin.5.en.html
https://manpages.debian.org/unstable/manpages/issue.5.en.html
https://manpages.debian.org/buster/manpages/motd.5.en.html
https://manpages.debian.org/buster/proftpd-basic/ftpusers.5.en.html
https://manpages.debian.org/buster/cron/crontab.1.en.html references cron.allow cron.disallow
https://manpages.debian.org/buster/login/login.1.en.html

**Comment by xen0vas** [comment]
Thanks for the feedback i will check

**Comment by xen0vas** [comment]
random crashes using getpwuid() . any ideas ? @alexmyczko

**Comment by alexmyczko** [comment]
i will need to check the source finding where you call it, but this should be helpful

https://pubs.opengroup.org/onlinepubs/9699919799/functions/getpwuid.html

can check later tonight

**Comment by xen0vas** [comment]
@alexmyczko ok the bug is fixed ! I used getpwuid_r()  instead of getpwuid() . I will upload the code asap

**Comment by xen0vas** [comment]
This issue is closed because the bug is fixed
